### ISSUE TITLE
I can help translate this great tutorial into Chinese

### ISSUE THREAD

**Issue by imxtx** [ToshioCP/Gtk4-tutorial#27]
Hi, Toshio. This tutorial is great, thus I want to help you translate it into Chinese. But I'm not familiar with ruby and front-end things. If you want to do this, too, you may need to 

1. Reorganize the `src` directory to better support multi-languages.
2. Add a language select button to the navigation bar.

I will be happy to translate this tutorial if you modify related files to support translation.

**Comment by ToshioCP** [comment]
Hi, T.X. Xie.

Thank you for your offer.
It is great that you translate the tutorial to Chinese.

I'd like to discuss it with you.

In my opinion, it is better to make another repository for the Chinese version.
Because I don't know Chinese at all and it's difficult for me to maintain the Chinese version.
The license of this tutorial is GPL, so anyone can translate, modify and distribute it.
It means that you can make your own repository for the Chinese version.

You can copy and use the ruby programs in this repository to make GFM, HTML and/or PDF from the source files (XXXX.src.md).
But you can use your own programs to do it or just write Markdown or HTML directly.
It is your choice.

I will put a link to your Chinese version in my tutorial.

I will be happy if you consider it.

Toshio Sekiya

**Comment by imxtx** [comment]
> Hi, T.X. Xie.
> 
> Thank you for your offer. It is great that you translate the tutorial to Chinese.
> 
> I'd like to discuss it with you.
> 
> In my opinion, it is better to make another repository for the Chinese version. Because I don't know Chinese at all and it's difficult for me to maintain the Chinese version. The license of this tutorial is GPL, so anyone can translate, modify and distribute it. It means that you can make your own repository for the Chinese version.
> 
> You can copy and use the ruby programs in this repository to make GFM, HTML and/or PDF from the source files (XXXX.src.md). But you can use your own programs to do it or just write Markdown or HTML directly. It is your choice.
> 
> I will put a link to your Chinese version in my tutorial.
> 
> I will be happy if you consider it.
> 
> Toshio Sekiya

Thank you for your reply. I've created a new repo for the Chinese version. 

Repo link: <https://github.com/imxtx/GTK4-tutorial-Chinese>

I will start to translate and update the readme file later today. I think I will be able to translate one section each day.

**Comment by ToshioCP** [comment]
Thank you for your help.
I saw the link you gave me.

Please tell me when you complete your repository.
Then I'll put the link to it in the Readme file of this ttutorial.

I'll keep this issue open until then.

**Comment by imxtx** [comment]
@ToshioCP I will let you know when I complete it. It may take few weeks.

**Comment by yihuajack** [comment]
@imxtx Thank you for your contribution; looking forward to later updates on the translated version!

**Comment by imxtx** [comment]
I've translated 9 chapters, but I will stop here because I'm too busy with my study. So I won't translate the rest of this good tutorial. I'm going to close this issue as not planned.
