### ISSUE TITLE
In Sec. 27 having FactoryList and FactoryGrid in separate .ui files instead of having it as GBytes in main ui file causes error

### ISSUE THREAD

**Issue by MightyPrince1** [ToshioCP/Gtk4-tutorial#31]
Probably something needs to be added for it to work as a seperate .ui file. It would be nice if this where to be fixed, as it is suggested at the end of the section as well as during the beginning.

error message:
Template declaration (class 'GtkListItem', parent 'GtkWidget') where templates aren't supported

**Comment by ToshioCP** [comment]
Thank you for the post, MughtyPrince1.

Today, I tested the program in `src/list4`, at which the separate ui files `factory_list.ui` and `factory_grid.ui` are located.

```
$ meson _build
The Meson build system
Version: 0.61.2
Source dir: /home/toshio/MYC/gtk4_tutorial/src/list4
Build dir: /home/toshio/MYC/gtk4_tutorial/src/list4/_build
Build type: native build
Project name: list4
Project version: undefined
C compiler for the host machine: cc (gcc 11.2.0 "cc (Ubuntu 11.2.0-19ubuntu1) 11.2.0")
C linker for the host machine: cc ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Run-time dependency gtk4 found: YES 4.6.5
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Program glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Build targets in project: 3

Found ninja-1.10.1 at /usr/bin/ninja
$ ninja -C _build
ninja: Entering directory `_build'
[5/5] Linking target list4
$ _build/list4
```

Then the program `list4` worked.

So, I'd ike you to compile like this so that you could avoid the error.

The source files are in `src/list4`.
If the source lists or explanation in the section 27 contains any difference from the source files in `src/list4`, please post a message to this issue thread.

Regards,

Toshio Sekiya

**Comment by ToshioCP** [comment]
It seems that there's no more question to this issue.
Therefore, the issue is closed.
