### ISSUE TITLE
rake html command produces different format

### ISSUE THREAD

**Issue by yihuajack** [ToshioCP/Gtk4-tutorial#41]
When I test my PR #40 I found that if I run `rake html`, then in every generated HTML file, all the text inside an element are not line-broken like this:
![Screenshot from 2023-01-19 13-31-44](https://user-images.githubusercontent.com/23608500/213363266-f40b0973-f979-4af8-8547-0b453bc4541a.png)
Are there any extra configurations needed for automatically do line breaks with fixed letters in a line? I didn't find that in Readme_for_developers; lib_mk_html_template.rb and Rakefile not modified

**Comment by ToshioCP** [comment]
Thank you for posting the issue, Yihua.

I think the line break is done by Pandoc.
However, browsers display the paragraph in the same style.
That means either output doesn't have problems.

Markdown recognizes a newline as a blank. It is called "softbreak".
Because newline is softbreak, pandoc can translate a newline to a blank and vice versa.
So, it can put a newline at any blank or no newline.
You can control it by --column option. It gives a line length to your pandoc.
The default is 72.
So, my output lines are broken around 72 characters. 

There's no relation between the line breaking and Rakefile.

Is the comment help you?
If not, additional question is welcome.

Toshio Sekiya

**Comment by ToshioCP** [comment]
My pandoc version is:
pandoc 2.17.1.1  --  Ubuntu 22.10 (kinetic) package

It is obvious that the line break is done by pandoc.
(Rakefile doesn't use pandoc when it generates GFM.)

I mistook the option name, --columns (s is added) is correct.
I tested this option as follows:

First, create a file "test.md".
test.md:
abc
abc
... ... ... (repeat the same line 10 times)

Then,

~~~
$ pandoc --columns=10 test.md -o test.html
$ cat test.html
<p>abc abc
abc abc
abc abc
abc abc
abc
abc</p>
$ pandoc --columns=20 test.md -o test.html
$ cat test.html
<p>abc abc abc abc
abc abc abc abc abc
abc</p>
$
~~~

HTML files depend on pandoc anyway.
So, HTML files can be different in the different environment.
If we wanted to avoid this, pandoc could not be used.
But, in my opinion, it makes too much work for a developer and not a good choice.

The different HTML generation is not a serious problem.
So, I will keep it (Rakefile) as it is now.
If you have better idea, please let me know.
