### ISSUE TITLE
A deep GObject tutorial

### ISSUE THREAD

**Issue by igormorgado** [ToshioCP/Gtk4-tutorial#6]
Hello! This is not a issue, but a request (very politely).

First of all thank you very much for your tutorial and code examples, it is helping me a lot in process.

I would like to ask you for a more complete tutorial section regarding GObject, can you do it?

Thank you, and keep your amazing work.

**Comment by ToshioCP** [comment]
Dear Igor,

Thank you for asking me a question.
First, I want to tell you my tutorial sections with regard to GObject.

- Section 7, "How to define a child widget of GtkTextView" subsection
- Section10
- Section20, "Preference dialog", "Alert dialog" subsections

 They are mainly about how to define child object. Because Defining child object is the most often used by programmers. However, other topics, for example, type system, implementing interface or properties, are also important. Maybe they are intermediate level topics.

I am writing about GtkListView and GtkColumnView. And I'm afraid that I don't have enough time to write gobject topics above now. But it's possible for me to write them in the future.
What I recommend you is to read GObject API reference. It is difficult for beginners, but it contains everything important about gobject. And if you have some specific questions, you can ask them here in the issue, or maybe gnome discourse (https://discourse.gnome.org/ ). Gnome discourse is very useful because the gtk developers answer the questions.
 
Toshio Sekiya

**Comment by igormorgado** [comment]
Hello ToshioCP, 

I have read all these sections, they are all well written and meaningful, but they are focused on your test application. I think it lacks details about how GObject behaves, the commonly used GLib/GTK macros, the generated boilerplate code. 

I have tried to study from GObject API reference, but, I must be honest, I could not follow it very well, hence I came here to ask for directions. I also tried the discourse, but with very small success.

Of course, this is just a humble request, not an order. I really enjoyed your tutorial, it is very well written and contains many details.

I will keep following up on your updates, and thank you, one more time.

**Comment by ToshioCP** [comment]
Dear Igor,

Thank you for giving me a comment again.
I've decided to begin writing "Gobject tutorial".
I'll create another repository for that.
I will upload contents section by section.

However, maybe the contents above will be a bit abstract and theoritical.
So, it is probably better to learn gtk4 (specific topics) first.
Anyway, if you have specific questions, feel free to ask me.

Toshio Sekiya

**Comment by ToshioCP** [comment]
Close the issue because "GObject tutorial" repository has been created.
